spring:
  application:
     name: fukun-search-es
  rabbitmq:
       addresses: 192.168.0.43:5672
       host: 192.168.0.43
       port: 5672
       username: guest
       password: guest
       virtual-host: /
       connection-timeout: 15000
       #消息发送到交换机确认机制,是否确认回调
       publisher-confirms: true
       #消息发送到交换机确认机制,是否返回回馈
       publisher-returns: true
  #     template.mandatory: true
       listener:
         simple:
  #         # 手动应答
           acknowledge-mode: manual
         direct:
          # 配置该消费者的ack方式为手动(消费者的ack方式默认是自动的，也就是说消息一旦被消费（无论是否处理成功），消息都会被确认，然后会从队列中删除)
           acknowledge-mode: manual
  main:
      allow-bean-definition-overriding: true

server:
 port: 8008

es:
  host: 192.168.0.43
  port: 9200
  protocol: http

