spring:
  application:
     name: fukun-core-config-server
  cloud:
     consul:
        host: localhost
        port: 8500
        discovery:
          enabled: true
          register: true
          tags: config-server
          serviceName: ${spring.application.name}
          hostname: ${spring.application.name}
          port: ${server.port}
          instanceId: ${spring.application.name}:${server.port}
          preferIpAddress: true
          healthCheckInterval: 10s
          healthCheckUrl: http://${spring.cloud.client.ip-address}:${server.port}/health
          heartbeat:
             enabled: true
     config:
        server:
          git:
             # 配置git仓库的地址
            uri: https://gitee.com/tangyifei/micro-service-architecture.git
            # git仓库地址下的相对地址，可以配置多个，用,分割。
            search-paths: config-repo
            # git仓库的账号
            username: 15062230055@163.com
            # git仓库的密码
            password:
  rabbitmq:
      host: 115.159.201.120
      port: 5672
      username: guest
      password: guest

server:
 port: 8889

management:
   endpoints:
      web:
        exposure:
             include: '*'




