spring:
  application:
     name: fukun-core-admin-client
  main:
    allow-bean-definition-overriding: true

  cloud:
     consul:
        host: localhost
        port: 8500
        discovery:
          enabled: true
          register: true
          tags: admin-client
          serviceName: ${spring.application.name}
          hostname: ${spring.application.name}
          port: ${server.port}
          instanceId: ${spring.application.name}:${server.port}
          preferIpAddress: true
          healthCheckInterval: 10s
          healthCheckUrl: http://${spring.cloud.client.ip-address}:${server.port}/health
          heartbeat:
             enabled: true

server:
 port: 8883

# Spring Boot2.x中，默认只开放了info、health两个端点，剩余的需要自己通过配置management.endpoints.web.exposure.include属性来加载
# 这个management.endpoints.web.base-path属性比较重要，因为Spring Boot2.x后每个端点默认的路径是/actuator/endpointId这样一来Spring Boot Admin是无法正常采集的
management:
   endpoints:
     web:
       exposure:
         include: "*"
       #  比较重要,默认 /actuator spring-boot-admin 扫描不到
#       base-path: /
#       path-mapping:
#         health: /health

   endpoint:
       health:
         show-details: ALWAYS

# 描述信息
info:
   blog-url: http://blog.battcn.com
   author: tangyifei
   # 如果 Maven 插件没配置此处请注释掉
   version: @project.version@
   name: @project.artifactId@

#LOGGING CONFIG
logging:
   config: classpath:logging/logback.xml
   level:
      root: info


